// packages/motion-gpu/src/lib/react/Portal.tsx
import { useEffect, useState, type ReactNode } from 'react';
import { createPortal } from 'react-dom';

export interface PortalProps {
	target?: string | HTMLElement | null;
	children?: ReactNode;
}

function resolveTargetElement(input: string | HTMLElement | null | undefined): HTMLElement {
	if (typeof document === 'undefined') {
		throw new Error('Portal target resolution requires a browser environment');
	}

	return typeof input === 'string'
		? (document.querySelector<HTMLElement>(input) ?? document.body)
		: (input ?? document.body);
}

export function Portal({ target = 'body', children }: PortalProps) {
	const [targetElement, setTargetElement] = useState<HTMLElement | null>(null);

	useEffect(() => {
		if (typeof document === 'undefined') {
			return;
		}
		setTargetElement(resolveTargetElement(target));
	}, [target]);

	if (!targetElement) {
		return null;
	}

	return createPortal(children ?? null, targetElement);
}

// packages/motion-gpu/src/lib/vue/Portal.vue
<script setup lang="ts">
import { computed } from 'vue';

interface Props {
	target?: string | HTMLElement | null;
}

const props = withDefaults(defineProps<Props>(), {
	target: 'body'
});

defineSlots<{
	default(): unknown;
}>();

/**
 * Resolves a teleport target to a concrete DOM element, falling back to body.
 */
function resolveTargetElement(input: string | HTMLElement | null | undefined): HTMLElement | string {
	if (typeof input === 'string') {
		if (typeof document === 'undefined') {
			return input;
		}

		return document.querySelector<HTMLElement>(input) ?? document.body;
	}

	if (input) {
		return input;
	}

	return typeof document === 'undefined' ? 'body' : document.body;
}

const teleportTarget = computed(() => resolveTargetElement(props.target));
</script>

<template>
	<Teleport :to="teleportTarget">
		<div class="motiongpu-portal-root">
			<slot />
		</div>
	</Teleport>
</template>
